/*
    File:    fox_scaner_keyword_table.cpp
    Created: 19 April 2019 at 11:41 Moscow time
    Author:  Сарыкова Анастасия Александровна
    E-mails: nastya.s@gmail.com
*/

#include "../include/fox_scaner_keyword_table.h"

namespace fox_scanner{
    const trans_table::Elem<Lexem_code> keywords_jump_table[] = {
        {const_cast<char32_t*>(U"езо"),  Lexem_code::Id,                 1}, // 0:   б...
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,                 4}, // 1:   бе...
        {const_cast<char32_t*>(U"1368"), Lexem_code::Kw_bz,              5}, // 2:   бз...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                 9}, // 3:   бо...
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,                10}, // 4:   бес...
        {const_cast<char32_t*>(U"26"),   Lexem_code::Id,                11}, // 5:   бз1...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,                13}, // 6:   бз3...
        {const_cast<char32_t*>(U"4"),    Lexem_code::Id,                14}, // 7:   бз6...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_bz8,             0}, // 8:   бз8
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_bol,             0}, // 9:   бол
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,                15}, // 10:  беск...
        {const_cast<char32_t*>(U"8"),    Lexem_code::Id,                16}, // 11:  бз12...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_bz16,            0}, // 12:  бз16
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_bz32,            0}, // 13:  бз32
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_bz64,            0}, // 14:  бз64
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,                17}, // 15:  беско...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_bz128,           0}, // 16:  бз128
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_beckon,          0}, // 17:  бескон
        
        {const_cast<char32_t*>(U"еоы"),  Lexem_code::Kw_v,              19}, // 18:  в...
        {const_cast<char32_t*>(U"щ"),    Lexem_code::Id,                22}, // 19:  ве...
        {const_cast<char32_t*>(U"з"),    Lexem_code::Id,                23}, // 20:  во...
        {const_cast<char32_t*>(U"бдх"),  Lexem_code::Id,                24}, // 21:  вы...
        {const_cast<char32_t*>(U"1368"), Lexem_code::Kw_veshch,         27}, // 22:  вещ...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,                31}, // 23:  воз...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,                32}, // 24:  выб...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,                33}, // 25:  выд...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,                34}, // 26:  вых...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,                35}, // 27:  вещ1...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,                36}, // 28:  вещ3...
        {const_cast<char32_t*>(U"4"),    Lexem_code::Id,                37}, // 29:  вещ6...
        {const_cast<char32_t*>(U"0"),    Lexem_code::Id,                38}, // 30:  вещ8...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,                39}, // 31:  возв...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,                40}, // 32:  выбо...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                41}, // 33:  выде...
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,                42}, // 34:  выхо...
        {const_cast<char32_t*>(U"8"),    Lexem_code::Id,                43}, // 35:  вещ12...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_veshch32,        0}, // 36:  вещ32
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_veshch64,        0}, // 37:  вещ64
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_veshch80,        0}, // 38:  вещ80
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,                44}, // 39:  возвр...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_vybor,           0}, // 40:  выбор
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_vydel,           0}, // 41:  выдел
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_vyxod,           0}, // 42:  выход
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_veshch128,       0}, // 43:  вещ128
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,                45}, // 44:  возвра...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_vozvrat,         0}, // 45:  возврат
        
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                47}, // 46:  г...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,                48}, // 47:  гл...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,                49}, // 48:  гла...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_glav,            0}, // 49:  глав

        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                51}, // 50:  д...
        {const_cast<char32_t*>(U"я"),    Lexem_code::Id,                52}, // 51:  дл...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_dlya,            0}, // 52:  для

        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,                54}, // 53:  е...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                55}, // 54:  ес...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,                56}, // 55:  есл...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_esli,            0}, // 56:  если

        {const_cast<char32_t*>(U"нс"),   Lexem_code::Id,                58}, // 57:  и...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,                60}, // 58:  ин...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,                61}, // 59:  ис...
        {const_cast<char32_t*>(U"ч"),    Lexem_code::Id,                62}, // 60:  ина...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,                63}, // 61:  ист...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,                64}, // 62:  инач...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,                65}, // 63:  исти...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Kw_inache,         66}, // 64:  иначе...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,                67}, // 65:  истин...
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,                68}, // 66:  иначее...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_istina,          0}, // 67:  истина
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                69}, // 68:  иначеес...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,                70}, // 69:  иначеесл...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_inacheesli,      0}, // 70:  иначеесли
        
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,                72}, // 71:  к...
        {const_cast<char32_t*>(U"мн"),   Lexem_code::Id,                73}, // 72:  ко...
        {const_cast<char32_t*>(U"п"),    Lexem_code::Id,                75}, // 73:  ком...
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,                76}, // 74:  кон...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                77}, // 75:  комп...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,                78}, // 76:  конс...
        {const_cast<char32_t*>(U"1368"), Lexem_code::Kw_kompl,          79}, // 77:  компл...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_konst,           0}, // 78:  конст
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,                83}, // 79:  компл1...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,                84}, // 80:  компл3...
        {const_cast<char32_t*>(U"4"),    Lexem_code::Id,                85}, // 81:  компл6...
        {const_cast<char32_t*>(U"0"),    Lexem_code::Id,                86}, // 82:  компл8...
        {const_cast<char32_t*>(U"8"),    Lexem_code::Id,                87}, // 83:  компл12...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_kompl32,         0}, // 84:  компл32
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_kompl64,         0}, // 85:  компл64
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_kompl80,         0}, // 86:  компл80
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_kompl128,        0}, // 87:  компл128

        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,                89}, // 88:  л...
        {const_cast<char32_t*>(U"гж"),   Lexem_code::Id,                90}, // 89:  ло...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,                92}, // 90:  лог...
        {const_cast<char32_t*>(U"ь"),    Lexem_code::Id,                93}, // 91:  лож...
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,                94}, // 92:  логи...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_lozh,            0}, // 93:  ложь
        {const_cast<char32_t*>(U"1368"), Lexem_code::Kw_logik,          95}, // 94:  логик...
        {const_cast<char32_t*>(U"6"),    Lexem_code::Id,                99}, // 95:  логик1...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,               100}, // 96:  логик3...
        {const_cast<char32_t*>(U"4"),    Lexem_code::Id,               101}, // 97:  логик6...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_logik8,          0}, // 98:  логик8
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_logik16,         0}, // 99:  логик16
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_logik32,         0}, // 100: логик32
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_logik64,         0}, // 101: логик64
        
        {const_cast<char32_t*>(U"ано"),  Lexem_code::Id,               103}, // 102: м...
        {const_cast<char32_t*>(U"лс"),   Lexem_code::Id,               106}, // 103: ма...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               108}, // 104: мн...
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,               109}, // 105: мо...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_mal,             0}, // 106: мал
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,               110}, // 107: мас...
        {const_cast<char32_t*>(U"ж"),    Lexem_code::Id,               111}, // 108: мно...
        {const_cast<char32_t*>(U"у"),    Lexem_code::Id,               112}, // 109: мод...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               113}, // 110: масс...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               114}, // 111: множ...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,               115}, // 112: моду...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,               116}, // 113: масси...
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,               117}, // 114: множе...
        {const_cast<char32_t*>(U"ь"),    Lexem_code::Id,               118}, // 115: модул...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_massiv,          0}, // 116: массив
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,               119}, // 117: множес...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_modul,           0}, // 118: модуль
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,               120}, // 119: множест...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               121}, // 120: множеств...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_mnozhestvo,      0}, // 121: множество
        
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               123}, // 122: н...
        {const_cast<char32_t*>(U"ч"),    Lexem_code::Id,               124}, // 123: ни...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               125}, // 124: нич...
        {const_cast<char32_t*>(U"г"),    Lexem_code::Id,               126}, // 125: ниче...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               127}, // 126: ничег...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_nichego,         0}, // 127: ничего
        
        {const_cast<char32_t*>(U"ч"),    Lexem_code::Id,               129}, // 128: о...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               130}, // 129: оч...
        {const_cast<char32_t*>(U"щ"),    Lexem_code::Id,               131}, // 130: очи...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_ochishch,        0}, // 131: очищ
        
        {const_cast<char32_t*>(U"ео"),   Lexem_code::Id,               133}, // 132: п...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,               135}, // 133: пе...
        {const_cast<char32_t*>(U"вк"),   Lexem_code::Id,               136}, // 134: по...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               138}, // 135: пер...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,               139}, // 136: пов...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               140}, // 137: пок...
        {const_cast<char32_t*>(U"мч"),   Lexem_code::Id,               141}, // 138: пере...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_povt,            0}, // 139: повт
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_poka,            0}, // 140: пока
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_perem,           0}, // 141: перем
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               143}, // 142: переч...
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,               144}, // 143: перечи...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,               145}, // 144: перечис...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               146}, // 145: перечисл...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,               147}, // 146: перечисле...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               148}, // 147: перечислен...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               149}, // 148: перечислени...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_perechislenie,   0}, // 149: перечисление
        
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               151}, // 150: р...
        {const_cast<char32_t*>(U"з"),    Lexem_code::Id,               152}, // 151: ра...
        {const_cast<char32_t*>(U"б"),    Lexem_code::Id,               153}, // 152: раз...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               154}, // 153: разб...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,               155}, // 154: разбо...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_razbor,          0}, // 155: разбор

        {const_cast<char32_t*>(U"ист"),  Lexem_code::Id,               157}, // 156: с...
        {const_cast<char32_t*>(U"м"),    Lexem_code::Id,               160}, // 157: си...
        {const_cast<char32_t*>(U"ы"),    Lexem_code::Id,               161}, // 158: сс...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,               162}, // 159: ст...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,               163}, // 160: сим...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,               164}, // 161: ссы...
        {const_cast<char32_t*>(U"оу"),   Lexem_code::Id,               165}, // 162: стр...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_simv,            0}, // 163: симв
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,               167}, // 164: ссыл...
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,               168}, // 165: стро...
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,               169}, // 166: стру...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               170}, // 167: ссылк...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               171}, // 168: строк...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,               172}, // 169: струк...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_ssylka,          0}, // 170: ссылка
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_stroka,          0}, // 171: строка
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_struk,           0}, // 172: структ
        
        {const_cast<char32_t*>(U"ио"),   Lexem_code::Id,               174}, // 173: т...
        {const_cast<char32_t*>(U"п"),    Lexem_code::Id,               176}, // 174: ти...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_to,              0}, // 175: то
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_tip,             0}, // 176: тип
        
        {const_cast<char32_t*>(U"у"),    Lexem_code::Id,               178}, // 177: ф...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,               179}, // 178: фу...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_fun,             0}, // 179: фун
        
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               181}, // 180: ч...
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,               182}, // 181: чи...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,               183}, // 182: чис...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               184}, // 183: чист...
        {const_cast<char32_t*>(U"я"),    Lexem_code::Id,               185}, // 184: чиста...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_chistaya,        0}, // 185: чистая
       
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               187}, // 186: ц...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,               188}, // 187: це...
        {const_cast<char32_t*>(U"1368"), Lexem_code::Kw_tsel,          189}, // 188: цел...
        {const_cast<char32_t*>(U"26"),   Lexem_code::Id,               194}, // 189: цел1...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,               195}, // 190: цел3...
        {const_cast<char32_t*>(U"4"),    Lexem_code::Id,               196}, // 191: цел6...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_tsel8,           0}, // 192: цел8
        {const_cast<char32_t*>(U"8"),    Lexem_code::Id,               197}, // 193: цел12...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_tsel16,          0}, // 194: цел16
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_tsel32,          0}, // 195: цел32
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_tsel64,          0}, // 196: цел64
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_tsel128,         0}, // 197: цел128
    };
};
